#!/bin/bash
#################################################################################
# Description   : Script permettant le telechargement de video youtube          #
# au meilleur format possible.                                                  #
# Necessite youtube-dl et ffmpeg                                                #
# Usage         : catchit <youtube-url>                                         #
#                                                                               #
# Suivi version :                                                               #
#  V   | Date     | Auteur           | Description des modifications            #
# ­­­­­|­­­­­­­­­­|­­­­­­­­­­­­­­­­­­|­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­­#
#  0.9 | 20170301 | antoine          | Creation                                 #
#################################################################################

if [ $# = 1 ] # Verification du nombre d'arguments
then
    if test -e /usr/local/bin/youtube-dl; then # Si youtube-dl est installer
	echo "[OK] youtube-dl is installed at /usr/local/bin/youtube-dl"
	if test -e /usr/bin/ffmpeg; then # Si ffmpeg est installer
	    echo "[OK] ffmpeg is installed at /usr/bin/ffmpeg"
	    # Get best format
	    if formatLine=$(/usr/local/bin/youtube-dl --list-formats $1 | grep 'best'); then 
		echo "[OK] Get best format for download"
		IFS=' ' read -r -a format <<< "$formatLine" # Recupere l'id du meilleur format
		# Telecharge la video dans le meilleur format et le place dans /$HOME/Musique
		if /usr/local/bin/youtube-dl -x -f ${format[0]} --output "$HOME/Musique/%(title)s.%(ext)s" $1
		then
		    echo "[OK] Successfull download"
		fi
	    fi
	else
	    echo "[ERROR] Need to install ffmpeg" 1>&2
	    exit 1
	fi
    else
	echo "[ERROR] Need to install youtube-dl" 1>&2
	exit 1
    fi
else
    echo "Usage: catchit <youtube-url>" 1>&2
    exit 1
fi